### ISSUE TITLE
zxhnh288a_hv11_fv110_gr51t17_firmware user

### ISSUE THREAD

**Issue by islamelasal** [MariosK239/Gr_ISP_Router_Firmware#1]
zxhnh288a_hv11_fv110_gr51t17_firmware.bin
please tell us username and password for this firmware?
thank you

**Comment by Esoshawqi** [comment]
Password and user?

**Comment by k-marios** [comment]
If the username/password on the routers label doesn't work, you could try "user" as username and leaving the password field blank. There is currently no known root password for this firmware.

**Comment by Esoshawqi** [comment]
Thanks so much

**Comment by islamelasal** [comment]
> 

i try it but more feathers off i want control all settings .. or surprise us with  a new software full access anf full feathers .. thankyou soo much

**Comment by k-marios** [comment]
If you try the previous version (gr51t16) the root credentials are available, i had forgotten about it.
username: forthnet
password: F0rth@c$n3t#

**Comment by verspielt** [comment]
ist das Admin Passwort schon bekannt? das hier angegeben geht nicht.

**Comment by k-marios** [comment]
Which firmware have you flashed? 
Have you tried a factory reset?

**Comment by verspielt** [comment]
Hallo ich habe die zxhnh288a_hv11_fv110_gr51t17_firmware.bin und ja habe auch versucht schon einen Werksreset versucht. habe es aber mittlerweile gefunden 
username: Nova_admin
passwort: dxEh-eNc.Lk7

**Comment by k-marios** [comment]
That's good! Thanks for the info.

**Comment by spinalgr1990** [comment]
Root Password for ZTE H288A


Username : Nova_admin
Password : dxEh-eNc.Lk7

or

Username: forthnet
Password: F0rth@c$n3t#
