### ISSUE TITLE
h188a/h288a

### ISSUE THREAD

**Issue by Tornado798DH** [MariosK239/Gr_ISP_Router_Firmware#4]
can you gave us vodafone firmware for h188a/h288a

**Comment by k-marios** [comment]
Hi! Vodafone does not use these router models in Greece.

**Comment by Tornado798DH** [comment]
i have we isp firmware
but not work on anothers isp
can you make it works
cause theres is @tedata.net.eg at the end of the username
can be delted ???
[h188a we.zip](https://github.com/k-marios/Gr_ISP_Router_Firmware/files/12813854/h188a.we.zip)

**Comment by Tornado798DH** [comment]
+vodafone egypt uses the h188a but i cannot get the firmware
