### ISSUE TITLE
DG8245V ISSUE / PASS/USER

### ISSUE THREAD

**Issue by Salemigo** [MariosK239/Gr_ISP_Router_Firmware#5]
the existing username and password are not working on it 
user: Nova_admin
pass: dxEh-eNc.Lk7
any help with that 
after resetting, the username and pass written on it work to open the settings. but 99.9% of options are locked and the update firmware option does not exist
I wish you guys can help <3 
![Huawei](https://github.com/user-attachments/assets/50998203-4965-4b10-9b58-e69415cb8dab)

**Comment by k-marios** [comment]
Hello!
The username/password combinations provided here only work on routers supplied by greek isps as mentioned in the readme. 
Thus, if your device has not been given out by cosmote, vodafone greece or nova greece, I'm afraid I can't help with this. 

You might find it useful to search in your country's telecom oriented forums for further information .

**Comment by Salemigo** [comment]
Thank you for your response and clarification.

I have already tried the default passwords for Huawei devices used in Egypt, including those related to major service providers like Vodafone Egypt. However, the issue persists, and I still cannot access the restricted options or the firmware update feature.

The device in question is provided by Vodafone Egypt. If there are any additional steps I can take or reliable resources you could recommend for further assistance, please let me know.

Thank you for your support!

**Comment by k-marios** [comment]
Hello!
I'm afraid I can't help you with this issue. If you'd like to gain root access some next steps may be establishing a UART connection by opening the device and dumping the flash to find the password. Though I have never attempted this before so i can't provide any more info.
Thanks for your feedback!
