### ISSUE TITLE
Missing vodafone retail firmware ZTE H267A

### ISSUE THREAD

**Issue by dracula99gr** [MariosK239/Gr_ISP_Router_Firmware#5]
Is there any retail version of that router available at all? 
![image](https://user-images.githubusercontent.com/20153526/209464986-48a94195-923c-4bb4-a2ee-b146c58856de.png)
The version my router currently is seems a little different (probably because it's the retail version)

**Comment by MariosK239** [comment]
I believe this is the firmware your router is running https://github.com/MariosK239/Gr_ISP_Router_Firmware/blob/main/Vodafone/Retail/ZTE/H267N/zxhnh267a_hv102_fv102_vdft21_firmware.bin . It is a retail/home version.

**Comment by dracula99gr** [comment]
> I believe this is the firmware your router is running https://github.com/MariosK239/Gr_ISP_Router_Firmware/blob/main/Vodafone/Retail/ZTE/H267N/zxhnh267a_hv102_fv102_vdft21_firmware.bin . It is a retail/home version.

Indeed sorry for the disturbance! Thank you very much and happy holidays!

I think it should be organized in a different folder because these routers aren't similar at all! The one is 5ghz capable the other isn't + etc

**Comment by MariosK239** [comment]
Yes i just realised the folder name is wrong. In a few days I'll reorganize it. Thanks for bringing up this issue!
